// Instalar a extensão "Rest Client" do VSCode

// Configurar o arquivo settings.json do VSCode :
// "rest-client.excludeHostsForProxy": ["localhost","127.0.0.1"]

@urlBase = http://localhost:3000

####################################################
## Login
####################################################

# @name login
#POST {{urlBase}}/auth/get_token
#Content-Type: application/json
#
#{
#  "username": "00000000002",
#  "password": "123456"
#}

###
#@token = {{login.response.body.$.token}}

################################
# CUSTOMERS
################################

# @name getAllCustomers
GET {{urlBase}}/customers

###

# @name addCustomer
POST {{urlBase}}/customers
Content-Type: application/json

{
    "type": "legal",
    "name": "IBM",
    "email": "ibm@gmail.com",
    "document": "48.290.111/0001-06"
}

###
@id = {{addCustomer.response.body.$.id}}

###

# @name getCustomerById
GET {{urlBase}}/customers/{{id}}

###

# @name putCustomer
PUT {{urlBase}}/customers/{{id}}
Content-Type: application/json

{
    "type": "legal",
    "name": "IBM (alt)",
    "email": "ibm@gmail.com",
    "document": "48.290.111/0001-06"
}

###

# @name deleteCustomer
DELETE {{urlBase}}/customers/{{id}}

###