// Instalar a extensão "Rest Client" do VSCode

// Configurar o arquivo settings.json do VSCode :
// "rest-client.excludeHostsForProxy": ["localhost","127.0.0.1"]

@urlBase = http://localhost:3000

####################################################
## Login
####################################################

# @name login
#POST {{urlBase}}/auth/get_token
#Content-Type: application/json
#
#{
#  "username": "00000000002",
#  "password": "123456"
#}

###
#@token = {{login.response.body.$.token}}

####################################################

################################
# CUSTOMERS
################################

# @name getAllCustomers
GET {{urlBase}}/customers

###

# @name addCustomer
POST {{urlBase}}/customers
Content-Type: application/json

{
    "type": "legal",
    "name": "IBM",
    "email": "ibm@gmail.com",
    "document": "48.290.111/0001-06"
}



# ###

# # @name getProductById
# GET {{urlBase}}/products/d5d3de57-c590-4735-a745-ba5645e74ab7



# ###

# # @name updateProduct
# PUT {{urlBase}}/products/d5d3de57-c590-4735-a745-ba5645e74ab7
# Content-Type: application/json

# {
#     "description": "Caneta Preta",
#     "price": 11
# }

# ###

# # @name deleteProduct
# DELETE {{urlBase}}/products/d5d3de57-c590-4735-a745-ba5645e74ab7


# ################################
# # TYPE PRODUCT
# ################################

# # @name getTypeProductById
# GET {{urlBase}}/type-products/728798a1-c4dd-4149-b30d-ecd54b9333a5

# ###

# # @name addTypeProduct
# POST {{urlBase}}/type-products
# Content-Type: application/json

# {
#     "description": "Material escritório"
# }

# ###

# # @name updateTypeProduct
# PUT {{urlBase}}/type-products/728798a1-c4dd-4149-b30d-ecd54b9333a5
# Content-Type: application/json

# {
#     "description": "Material escritório (alt)"
# }

# ###

# # @name deleteTypeProduct
# DELETE {{urlBase}}/type-products/728798a1-c4dd-4149-b30d-ecd54b9333a5